apiVersion: v1
kind: Secret
metadata:
    name: technitium-admin
    namespace: technitium
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5APas0p0T6i9,iv:gPvlrOGHTSqxI0DEceA4kQ4MbUFlDNrc7nA6E5VyoYk=,tag:Pz/rvZK49d1VZl1xOCYqjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1hXMzVsL1Nka0RTSmNF
            M2hMd3QyMU5LY2NIM0R1S1dyM0FsS0hGb2l3CmczL0lrMVVUbjU0blY4S21wT2RV
            bHp5VnFQSHZuYkQyaFFDVTBoQVk3clUKLS0tIElGMzQ1TW5yZHBJa1B6elBSbzdC
            dGkxQjdPd0ZVbzJNQ3U1S05HWlVzdEEKmbBvjFU5Hs6TacQw5R90txliAaF8f0SR
            BzEFAX3E9O8uOMf/7EWE7L8Icg+Cw6jjE1ob4gz3XRK3kDkl/y72xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T09:58:25Z"
    mac: ENC[AES256_GCM,data:8En8e5eC0kuYmHidyo7DJpuB1GHyi561DG5/ebLxSTPwvECBbikB22U95oxQox4biZRjnpyQSFI89662qDyKMHtbcyMRcYNOV7ITKdfWX9dPCq6Ph+Igyp/mCK3h0aW/NwOaJSWb7IWMJHP12EnxnBPpqiUWFiSBU3QAh/liSh8=,iv:M7UKm0/Z1ZsSK4cHgdeBCxUMqGQLUT6HlM5dp+59GG4=,tag:qbZsdpUh5B2W4l9eRTVCIA==,type:str]
    version: 3.13.3
