apiVersion: v1
kind: Secret
metadata:
    name: technitium-admin
    namespace: technitium
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:RmIXorM3AH6WeskHH9wQR7HgeAmU5tgv84QlE56sUbI=,iv:Ju0n4g6HvfCRcl6wIFg5LBMdkUp+Ik2dlys6nkeaqR0=,tag:xSNgjo0cykjwgHsXOj7kww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRkhqQWtEcElIeHhmU0Jx
            ZmlFRnl0SXZJVm9CbHdneGh6d2RCdFE2YW5VCmpJYUxWK0FLa3BEOEo5WU9ud0NQ
            MktTcndYS1NxYkJPUnBZTlpxTUVrMFEKLS0tIENyREg5SlVINUZXZnVObHkwcmh4
            NjRxU0tCQjlxZVlWcEEreGh4TThXM3cKYThiZ09wxTO4gpIXS1DpsR8SsqK7csxs
            f2narIqF5ndskJqBNvLTLxono3En2HxyXzHCPX8TbYd/xtOcr4Ggtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T04:29:00Z"
    mac: ENC[AES256_GCM,data:24hKIHmYBJ5A47860HOhuLtd6TWMWrXbsgUWBOp4MtC6TOnfnP19ZmjB1TSnksvtfxGCCgNJ37Imh0rTXxtcylNJfmNH1GDYtEYsDfM2QGPK+kX1kDuCnyIFeJsVVewGsf8db1oRvKGpCfESXxAdQGMqQIO1ywk3p8zWv01eSMk=,iv:wWXOQSQofZAeLcJzteYz0GoCdRY34zaQXu89x0Lk630=,tag:3Yq5R6u1pWKhtQELZLWTBA==,type:str]
    version: 3.13.3
