apiVersion: v1
data:
    token: ENC[AES256_GCM,data:LmmnyM7WxyrZSSdeAEo0HC+L//cj0Brq2xe94E9ovDdFLB3wHbGWLnUC8P3PPXtn,iv:gXA0SgGI57FMzpV+53R+LHbqoMvqZkjLhvTuVGH6Hfs=,tag:4MgmkW9uWmCvqTPjx5aKWw==,type:str]
kind: Secret
metadata:
    name: beszel-agent-token
    namespace: beszel-agent
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YzliSjI3UlZLamo5RUdU
            Z1pRUmV4RG1TNDVHcUV4UE5QaCs1REg1Tm5vCjJ2QlVHeWtMKzJCVk1KZXBIdW5v
            cmNGUzlrcjE3Qi9nV2ExcmRVL294clUKLS0tIC9ZdmJFRVgzQjY4akhiZHhpeHFP
            SnZzQlp3QjZ2Y0pSOUY4MUVVMFYyaDgKjNHpqgKQpST5nvlV/PovIPkPyIjtXy4g
            QIvE3vD42yVLM7KSi1Ii0mQGlVf4eJe9nVqqLCJnH3bfZZTewoHc7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T08:12:17Z"
    mac: ENC[AES256_GCM,data:QIjof7qdwcbBl7csdceF16aUHNgoBna0yKhr1PjXNhPMF3gVGiCXmGJ9rkulpAcu3nwdSTfSHoU2zkudANa0m02yoIPB3EUR4RQyi3VKaR2tYEjfQn+NazzJmsxMKI1Z8u64IPAA8zBO5ShAczncx7jsPlNpE+D7Tv1StcDPKoM=,iv:aPpcPFDaZQ9eYWC3eQOiUs2MJyYwTy4de9GGPPBNHDA=,tag:poKdW8mubU4+VkkXMnjdQQ==,type:str]
    version: 3.13.3
