clusterName: homelab
kubernetesVersion: v1.36.1
endpoint: https://192.168.10.107:6443


cniConfig:
  name: none

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        proxy:
          disabled: true


nodes:
  - hostname: cp1
    controlPlane: true
    ipAddress: 192.168.10.107
    installDisk: /dev/sda
  - hostname: cp2
    controlPlane: true
    ipAddress: 192.168.10.108
    installDisk: /dev/sda
  - hostname: cp3
    controlPlane: true
    ipAddress: 192.168.10.109
    installDisk: /dev/sda
