kubeProxy:
  enabled: false


kubeEtcd:
  enabled: true
  endpoints:
    - 192.168.10.107
    - 192.168.10.108
    - 192.168.10.109

prometheus:
  prometheusSpec:
    retention: 10d
    retentionSize: 18GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: truenas-iscsi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 20Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    resources:
      requests: {cpu: 200m, memory: 1Gi}
      limits: {memory: 3Gi}

grafana:
  admin:
    existingSecret: grafana-admin     
  persistence:
    enabled: true                     
    storageClassName: truenas-iscsi
    accessModes: [ReadWriteOnce]
    size: 5Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: truenas-iscsi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 2Gi