apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:b3ELeA==,iv:yzsCyFXHNBBZ20EQccGNmkjWZpV3V0W4oesR+4UrBDs=,tag:pLKq4xKmmk4Bd9yfa3A5aA==,type:str]
    admin-password: ENC[AES256_GCM,data:sj9IwgdZBIHF,iv:DJPeGPELq5dfdM2Ea1OfQww4RTMIRWld7lRT7uddNVg=,tag:3z4qqUl3A7RL1V3j9lV4IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbEpPL3dtRE5EMzFFZ000
            RTZvZGYwOTZpSXhtcmxVTkZUVG9ZVWk5RWgwCkU5ZCs3Tk1ZZmM4dUFNQzFNVWly
            MnI5QVJNc2ZWMHVqRFA3WUlZM2xyRnMKLS0tIGZCdjBZWk5xRVVDTTg3U245ejJC
            c3ZWZmJocEJlUDdpSkxmYzFTd25CL1kKyZbVEB5LheiKJxDK2depXyDOnurscE7t
            ny2NOh/eHxqET6Yo45W1YwsHe4W2ldLxYurcBZLmgl0BpRlexP1gCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T23:17:07Z"
    mac: ENC[AES256_GCM,data:CBEw7MixD/hN27NoGvjnRUs4lelyS1TXOaKeikvwFLGHqRRi07qI+04AV4NY2yZDqUh4/CLZSpdvcHJ1e49DjDyiyK54CaGzqS6d4aXhGGf9/uHiCORBT60mboWROQLi9ifg7nywRdgf/eJn53jKqmLmCz1h955gfp7HEmcaobs=,iv:AapN1o8x4RIzpaukuxvQ1KAKqfyhsnvR5QNz0smyzww=,tag:cygPTn4+wLZEayMALT9Rlw==,type:str]
    version: 3.13.3
