#       sops -e -i kubernetes/apps/infrastructure/democratic-csi/app/secret.sops.yaml
#
apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-secrets
    namespace: democratic-csi
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9PhVs82zd3JwWrFMkyA3L03qdxuituEQkhBOwNZnkua+idkwhBmqUrPIkxkxnNTZtAno8J39lLTqyX/HO69hgsxkbaK7VETp40ykLP9bjmvc6pBY1mFbQ/62klwr3r45ChLTMz1LkSyLcsxZUFh6Xfbeg5PXFlc=,iv:fwJyGkB46wkHdSE9JGg4uPvUuRvRkp9A3+m2viWTuDs=,tag:tAAfpnqeQgroBG2Mz4Ui/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDelNQRW9TNENtSmlGekQ2
            SzBuZXREUFdOQk1lOG5oQmpvVGt6c1Nxb3g0ClhneU12eXlGaC9vOVd5SGwxbkl0
            YkpYUlExWE80ckczWVJOMFlOMWVYM3cKLS0tIE5GcjdIOGkzdEE4QXlCeGFBYkIr
            ek5TWGhhOTBPSkRycmd3MkdQdXpsQnMK+hVDhrPoShrzCHwYXljLSKl1SFepLGza
            K5vf49BBRgd4lMd+rMbtUVBm2LYnxFLfx7ZZ4fpxujOJ4xDMcd5OZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1306vmgtph4w0ttdgxvp5lkn90da632qandaad2875hg0hrn9yfsqmta89v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T08:27:30Z"
    mac: ENC[AES256_GCM,data:vlkEN5906tVgLPGHile5wfCjVrWIcRHnr2f/M6g8410HQ9TyX9KwTehuMeVMnJpXLpYtIMjHzfB6jiOX/8Jb6OhNckyyz8rQglyzFwR/jI4ieXrybwt/RXWSeVfmX5GC+ukQeZGmJAOFD0GytqlnICgGZjj74XCRX2FmYTx6eag=,iv:j6BoYbIaSsfFTnADfBc2CmxTkbOKvLsau2o154mXR6U=,tag:tAO4DZbdEZIyDNywv8k01g==,type:str]
    version: 3.13.3
